[formatter.clang-format]
command  = "clang-format"
options  = ["-i"]
includes = ["*.c", "*.cpp", "*.cxx", "*.h", "*.hpp", "*.hxx"]

[formatter.cmake-format]
command  = "cmake-format"
options  = ["--in-place"]
includes = ["CMakeLists.txt", "*.cmake"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
]

[formatter.toml]
command  = "taplo"
options  = ["format", "$@"]
includes = ["*.toml"]

[formatter.nix]
command  = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.shell]
command = "sh"
options = ["-eucx", """
# Perform static analysis tool
shellcheck --external-sources --source-path=SCRIPTDIR "$@"

# Run formatter
shfmt --write --simplify --case-indent --indent 4 "$@"
    """, "--"]
includes = ["*.sh"]

[formatter.hcl]
command  = "hclfmt"
options  = ["-w"]
includes = ["*.hcl"]
