name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - ci/*
      - release/*

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot

      - name: Run GoReleaser release
        uses: goreleaser/goreleaser-action@v4
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
